name: CI

on:
  push:
    branches: [ main ]
    tags: '*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 21
          cache: 'maven'

      - name: Build with Maven
        run: mvn package

      - name: Deploy to AWS Lambda
        if: github.ref == 'refs/heads/main'
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          function_name: jmail-lambda
          zip_file: target/jmail-lambda-1.0.0-SNAPSHOT.jar

      - name: Wait for update
        if: github.ref == 'refs/heads/main'
        run: sleep 5

      - name: Test API
        if: github.ref == 'refs/heads/main'
        uses: lakuapik/gh-actions-http-status@v1
        with:
          sites: '["https://tnrrvxkpol.execute-api.us-east-1.amazonaws.com/prod/jmail?address=test@test.com", "https://tnrrvxkpol.execute-api.us-east-1.amazonaws.com/prod/jmail?address=error"]'
          expected: '[200, 400]'
